package com.work.correct.mapper;

import java.util.List;

import com.work.correct.model.HomeWork;

public interface HomeWorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbg.generated
     */
    int insert(HomeWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbg.generated
     */
    int insertSelective(HomeWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbg.generated
     */
     List<HomeWork>  selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HomeWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HomeWork record);
    List<HomeWork> selectAll();
    List<HomeWork> selectByname(String workname);
}