package com.work.correct.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.work.correct.model.Pro;

public interface ProMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbg.generated
     */
    int insert(Pro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbg.generated
     */
    int insertSelective(Pro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbg.generated
     */
    Pro selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Pro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Pro record);
    List<Pro> selectByStuid(String stuid);
    List<Pro> selectByHomeid(Integer homeid);
    List<Pro> selectByClassid(Integer classid);
    List<Pro> selectAll();
    List<Pro> selectPros(@Param("stuid")String stuid,@Param("homeid")Integer homeid,@Param("classid")Integer classid);
}