package com.work.correct.model;

public class HomeWork {
    @Override
	public String toString() {
		return "HomeWork [id=" + id + ", workname=" + workname + ", workcontent=" + workcontent + ", lasttime="
				+ lasttime + ", classid=" + classid + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.workname
     *
     * @mbg.generated
     */
    private String workname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.workcontent
     *
     * @mbg.generated
     */
    private String workcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.lasttime
     *
     * @mbg.generated
     */
    private String lasttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.classid
     *
     * @mbg.generated
     */
    private Integer classid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.id
     *
     * @return the value of homework.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.id
     *
     * @param id the value for homework.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.workname
     *
     * @return the value of homework.workname
     *
     * @mbg.generated
     */
    public String getWorkname() {
        return workname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.workname
     *
     * @param workname the value for homework.workname
     *
     * @mbg.generated
     */
    public void setWorkname(String workname) {
        this.workname = workname == null ? null : workname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.workcontent
     *
     * @return the value of homework.workcontent
     *
     * @mbg.generated
     */
    public String getWorkcontent() {
        return workcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.workcontent
     *
     * @param workcontent the value for homework.workcontent
     *
     * @mbg.generated
     */
    public void setWorkcontent(String workcontent) {
        this.workcontent = workcontent == null ? null : workcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.lasttime
     *
     * @return the value of homework.lasttime
     *
     * @mbg.generated
     */
    public String getLasttime() {
        return lasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.lasttime
     *
     * @param lasttime the value for homework.lasttime
     *
     * @mbg.generated
     */
    public void setLasttime(String lasttime) {
        this.lasttime = lasttime == null ? null : lasttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.classid
     *
     * @return the value of homework.classid
     *
     * @mbg.generated
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.classid
     *
     * @param classid the value for homework.classid
     *
     * @mbg.generated
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }
}