package com.work.correct.model;

public class Pro {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro.id
     *
     * @mbg.generated
     */
    private Integer id;
    private String teacherresult;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro.stuid
     *
     * @mbg.generated
     */
    private String stuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro.files
     *
     * @mbg.generated
     */
    private String files;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro.createtime
     *
     * @mbg.generated
     */
    private String createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro.isread
     *
     * @mbg.generated
     */
    private Integer isread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro.homeid
     *
     * @mbg.generated
     */
    private Integer homeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro.classid
     *
     * @mbg.generated
     */
    private Integer classid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro.id
     *
     * @return the value of pro.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro.id
     *
     * @param id the value for pro.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro.stuid
     *
     * @return the value of pro.stuid
     *
     * @mbg.generated
     */
    public String getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro.stuid
     *
     * @param stuid the value for pro.stuid
     *
     * @mbg.generated
     */
    public void setStuid(String stuid) {
        this.stuid = stuid == null ? null : stuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro.files
     *
     * @return the value of pro.files
     *
     * @mbg.generated
     */
    public String getFiles() {
        return files;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro.files
     *
     * @param files the value for pro.files
     *
     * @mbg.generated
     */
    public void setFiles(String files) {
        this.files = files == null ? null : files.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro.createtime
     *
     * @return the value of pro.createtime
     *
     * @mbg.generated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro.createtime
     *
     * @param createtime the value for pro.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro.score
     *
     * @return the value of pro.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro.score
     *
     * @param score the value for pro.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro.isread
     *
     * @return the value of pro.isread
     *
     * @mbg.generated
     */
    public Integer getIsread() {
        return isread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro.isread
     *
     * @param isread the value for pro.isread
     *
     * @mbg.generated
     */
    public void setIsread(Integer isread) {
        this.isread = isread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro.homeid
     *
     * @return the value of pro.homeid
     *
     * @mbg.generated
     */
    public Integer getHomeid() {
        return homeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro.homeid
     *
     * @param homeid the value for pro.homeid
     *
     * @mbg.generated
     */
    public void setHomeid(Integer homeid) {
        this.homeid = homeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro.classid
     *
     * @return the value of pro.classid
     *
     * @mbg.generated
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro.classid
     *
     * @param classid the value for pro.classid
     *
     * @mbg.generated
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

	public String getTeacherresult() {
		return teacherresult;
	}

	public void setTeacherresult(String teacherresult) {
		this.teacherresult = teacherresult;
	}
}