package com.work.correct.model;

public class StuClass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuclass.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuclass.stuid
     *
     * @mbg.generated
     */
    private String stuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stuclass.classid
     *
     * @mbg.generated
     */
    private Integer classid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuclass.id
     *
     * @return the value of stuclass.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuclass.id
     *
     * @param id the value for stuclass.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuclass.stuid
     *
     * @return the value of stuclass.stuid
     *
     * @mbg.generated
     */
    public String getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuclass.stuid
     *
     * @param stuid the value for stuclass.stuid
     *
     * @mbg.generated
     */
    public void setStuid(String stuid) {
        this.stuid = stuid == null ? null : stuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stuclass.classid
     *
     * @return the value of stuclass.classid
     *
     * @mbg.generated
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stuclass.classid
     *
     * @param classid the value for stuclass.classid
     *
     * @mbg.generated
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }
}